apiVersion: v1
kind: Service
metadata:  
  name: activityservice
  labels:
    run: activityservice  
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: activityservice
  type: NodePort